### ISSUE TITLE
issues de maintenance

### ISSUE THREAD

**Issue by revolunet** [betagouv/beta.gouv.fr#19247]
améliorations tech à apporter sur le repo: 

- localdev:
  - voir si possible d'améliorer le hot-reload sans rebuild toutes les fiches (#20423)
- extraire des fonctions/rewrite les templates complexes
- normaliser les images des SE?
- ⚠ pb de cache sur /assets (Ad dans nginx, mettre etag uniquement?) : si on modifie du CSS/JS, il n'est pas rechargé
- ~~search~~
- lenteur du build scalingo
- dans la fiche d'un produit, "les ancien(ne)s" s'affich meme s'il y en a pas : [exemple](https://beta.gouv.fr/startups/vert.impact.html)
```[tasklist]
### Tasks
- [ ] optimiser le processus de build
- [ ] normaliser les images des SE
- [x] lenteur du build Scalingo
- [ ] bug d'affichage des alumni
- [ ] problème avec les assets NGINX
```
