### ISSUE TITLE
Rendre 100% des données des fiches startups et membres accessible avec l'API

### ISSUE THREAD

**Issue by jdauphant** [betagouv/beta.gouv.fr#4353]
Pour le moment, seul une partie des données est accessible en API, rentre l'ensemble accessible.

To Do
- [ ] Toutes les données startups
- [ ] Toutes les données membres
- [ ] Les offres d'emplois ?
```[tasklist]
### Tasks
```

**Comment by Morendil** [comment]
Pourquoi ? Ca contribue à quel bénéfice ?

**Comment by jdauphant** [comment]
Je parle uniquement des données contenues 
Pour les données membres, on les utilisent dans le secretariat (la liste des startups de la personne peut être pratique pour gérer les DNS ou faire des rappels par équipe).
Pour les startups, j'ai besoins de plus de meta-data des fiches aussi, je vais faire un graphe pour tout visualiser (avec les sponsors).

**Comment by jdauphant** [comment]
Pour les offres d'emplois, ça pourrait servir aux autres incubateurs mais pas de besoins clair d'où le "?"

**Comment by jdauphant** [comment]
Une solution, automatiser la génération de https://github.com/betagouv/beta.gouv.fr/blob/master/api/v2.1/authors.json avec le code des fiches sans avoir à référencer tous les champs
