### ISSUE TITLE
Create a jobs navigation entry

### ISSUE THREAD

**Issue by maukoquiroga** [betagouv/beta.gouv.fr#740]
# Create a jobs navigation entry

### Objectif

Augmenter les leads des travailleurs et travailleuses numériques (recrutement)

### Histoire

	Quand j’en ai déjà eu assez sur un site administratif qui ne marche pas du tout,
	et que j’en ai marre de travailler tout·e seul·e,
	et que je suis un lien qui me mène sur beta.gouv.fr ;

	Je veux savoir qu’est-ce l’incubateur, 
	et savoir s’ils ont de postes ouverts,
	et être rassuré de ne pas candidater à des postes déjà pourvus,
	et pouvoir facilement identifier les postes les plus récents,
	et savoir quel est le produit où je serais mené·e à intervenir,
	et savoir quel serait mon rôle concrètement (no guru/ninja bullshit please),
	et savoir avec qui serais-je mené·e à travailler,
	et savoir quel serait l’impact de mon travail (no more Facebook of pets please),
	et si je serai payé·e justement,
	et si j’aurais une autonomie sur la techno,
	et si j’aurais une autonomie sur le mode de travail,
	et si j’aurais la possibilité de faire du libre
	et si j'ai l'expérience requise pour le poste,
	et quelles seraient mes conditions de travail ;
	
	Pour sentir l’accomplissement d’avoir un impact social,
	et être fière de mon travail,
	et pourquoi pas apporter au développement des communs numériques,
	en travaillant entouré·e d’une équipe top,
	et redonner du sens à mon métier,
	et, dis donc, apporter à faire évoluer ces sites administratifs qui me font chier ?

### Design Studio

<img width="1212" alt="landing jobs" src="https://user-images.githubusercontent.com/329236/26879419-5731d428-4b91-11e7-93f8-e0d9471cbb13.png">

### TODO

- [x] Ajoute une entrée recrutement #745 
- [x] Explicite sur quel produit interviendrait-on #745 
- [x] Explicite si le poste est encore ouvert #745
- [x] Met en évidence les postes à pourvoir #769 #784 #855 
- [x] Met en évidence les postes les plus récents #745 
- [x] Explicite le rôle recherché #745 
- [ ] Explicite l'équipe avec laquelle travaillerait-on #980 #981
- [ ] Explicite l'impact du rôle dans le réel
- [ ] Explicite les expectatives salariales / de remuneration
- [x] Explicite le degré d'autonomie sur la techno #815
- [ ] Explicite le degré d'autonomie sur le mode de travail (agile, lean, etc.)
- [ ] Explicite si le code du produit et les données produites sont ouvertes et/ou libres
- [ ] Explicite l'expérience requise pour le poste #825
- [ ] Explicite les modalités de travail (CDD, CDI, 3/5e, etc.)
- [ ] Permet de faire une candidature spontanée 

cc @MattiSG @gregoirenovel @Flightan @Ismael-Hery @Morendil 

(cf https://github.com/ackerdev/prog-etiquette/blob/master/JOBS.md)

**Comment by Morendil** [comment]
@maukoquiroga Il me semble que c'est implémenté pour l'essentiel ? On ferme ou on laisse ?

**Comment by Morendil** [comment]
Je ferme à nouveau cette issue sans avancées constatées sur un trimestre. Plutôt que la réouvrir j'invite à la morceler en tâches réalisables dans un temps relativement court.
