### ISSUE TITLE
Create a link between portfolio and job openings

### ISSUE THREAD

**Issue by maukoquiroga** [betagouv/beta.gouv.fr#764]
# Create a link between portfolio and job openings

### Objectif

Augmenter les leads des travailleurs et travailleuses numériques (recrutement)

### Histoire

	Quand je suis en train de chercher une nouvelle mission,	
	et que j’en ai marre de travailler tout·e seul·e,
	et que j’en ai le ras-le-bol des Tinder pour X,
	et que je suis un lien qui me mène sur beta.gouv.fr ;

	Je veux savoir ce qu’est l’incubateur,
	et savoir ce qu’on a fait ;

	Quand je découvre le showcase du portfolio,
	et qu’aucun produit ne m’intéresse ;

	Je veux jeter un coup d’oeil au portfolio complet ;

	Quand je repère la Boussole dont j’ai entendu parler,
	et que je lis le pitch du produit,
	et que je ressens que c’est un truc avec du sens ;

	Je veux savoir s’ils ont des postes ouverts,
	et savoir si l’équipe est sympa,
	ou à défaut savoir s’il y a d’autres postes à pourvoir ;
	
	Pour pouvoir mettre en exergue mes convictions,
	et mettre mes compétences au service d’une bonne cause,
	ou les Tinder pour X que j’ai déjà dû développer,
	et être entouré·e d’un group humain exceptionnel,
	et être fière de moi-même.

### Design Studio

<img width="1763" alt="landing startups startup 21-06-17 11 38 08 am" src="https://user-images.githubusercontent.com/329236/27377776-3744c464-5676-11e7-9bf4-e6eebe38ecbc.png">

### TODO

- [ ] Show 3 startups instead of 1 in landing
- [x] List job offers, if any open, per startup #769
- [x] Show team members #980 
- [ ] Show KPIs

**Comment by Morendil** [comment]
We're already showing 3 startups, and displaying KPI seems like a separate issue from that described, so I'm taking the liberty of closing this stale issue. Reopen if you feel something is still missing and there is consensus and energy for making progress on it.

**Comment by Morendil** [comment]
Je ferme à nouveau cette issue sans avancées constatées sur un trimestre. Plutôt que la réouvrir j'invite à la morceler en tâches réalisables dans un temps relativement court.
